[project]
name = "worker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Artem Kornilaev", email = "artemkornilaev1@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.43.110",
    "faster-whisper>=1.2.1",
    "pyannote-audio>=4.0.7",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
worker = "worker:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false

[dependency-groups]
dev = [
    "mypy>=2.4.0",
]
